language: python
python:
  - "2.7"
  - "3.3"


os: linux
dist: trusty
sudo: required

env:
  global:
    - HYDRA_LAUNCHER=fork
    - OMPI_MCA_rmaps_base_oversubscribe=yes
  matrix:
    - MPI=mpich
    - MPI=openmpi

matrix:
  include:
    - os: osx
      env: MPI=mpich PY=2
      language: generic
      python: 2
    - os: osx
      env: MPI=openmpi PY=2
      language: generic
      python: 2
    - os: osx
      env: MPI=mpich PY=3
      language: generic
      python: 3
    - os: osx
      env: MPI=openmpi PY=3
      language: generic
      python: 3
    - python: pypy2.7-5.10.0
      env: MPI=mpich
    - python: pypy2.7-5.10.0
      env: MPI=openmpi
    - python: pypy3.5-5.10.0
      env: MPI=mpich
    - python: pypy3.5-5.10.0
      env: MPI=openmpi
  allow_failures:
    - python: pypy2.7-5.10.0
      env: MPI=mpich
    - python: pypy2.7-5.10.0
      env: MPI=openmpi
    - python: pypy3.5-5.10.0
      env: MPI=mpich
    - python: pypy3.5-5.10.0
      env: MPI=openmpi



install:
  - pip install -r requirements.txt





script:
  - pytest