language: python
dist: trusty

# (Pre)Installation
# Test matrix for different C & fortran compilers
matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - gfortran-4.9
            - g++-4.9
            - openmpi-bin
            - openmpi-common
            - libopenmpi-dev
            # numpy (and more)
            - libopenblas-base
            # Planck likelihood
            - liblapack3
            - liblapack-dev
      env:
        - GCC_VERSION="4.9"
        - PYVER="2"
      python: "2.7"
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - gfortran-7
            - g++-7
            - openmpi-bin
            - openmpi-common
            - libopenmpi-dev
            # numpy (and more)
            - libopenblas-base
            # Planck likelihood
            - liblapack3
            - liblapack-dev
      env:
        - GCC_VERSION="7"
        - PYVER="2"
      python: "2.7"
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
            - g++-5
            - openmpi-bin
            - openmpi-common
            - libopenmpi-dev
            # numpy (and more)
            - libopenblas-base
            # Planck likelihood
            - liblapack3
            - liblapack-dev
      env:
        - GCC_VERSION="5"
        - PYVER="3"
      python: "3.6"
    # BELOW: CAMB devel #################################################
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - gfortran-6
            - g++-6
            - openmpi-bin
            - openmpi-common
            - libopenmpi-dev
            # numpy (and more)
            - libopenblas-base
            # Planck likelihood
            - liblapack3
            - liblapack-dev
      env:
        - GCC_VERSION="6"
        - PYVER="2"
        - CAMB_BRANCH="devel"
      python: "2.7"
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - gfortran-6
            - g++-6
            - openmpi-bin
            - openmpi-common
            - libopenmpi-dev
            # numpy (and more)
            - libopenblas-base
            # Planck likelihood
            - liblapack3
            - liblapack-dev
      env:
        - GCC_VERSION="6"
        - PYVER="3"
        - CAMB_BRANCH="devel"
      python: "3.6"
###############################################################################
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-"${GCC_VERSION}" 90
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-"${GCC_VERSION}" 90
  # optional, but necessary for tests
  - pip install mpi4py pytest-xdist flaky matplotlib




script:
  - pytest